 CREATE TABLE LANG_MAST(
 lang_id INT auto_increment,
 lang varchar(30),
 primary key(lang_id));
 
 CREATE TABLE ACT_MAST(
 act_id INT auto_increment,
 act_name varchar(50),
 primary key(act_id));
 
 CREATE TABLE DIR_MAST(
 dir_id int auto_increment,
 dir_name varchar(100),
 primary key(dir_id));
 
 CREATE TABLE MOV_NORM(
 rel_year int,
 mov_name varchar(100),
 lang_id int,
 dir_id int,
 act_id int,
 FOREIGN KEY (lang_id) REFERENCES LANG_MAST(lang_id),
 FOREIGN KEY (act_id) REFERENCES ACT_MAST(act_id),
 FOREIGN KEY (dir_id) REFERENCES DIR_MAST(dir_id));

SELECT * FROM MOV_NORM;
SELECT * FROM ACT_MAST;
SELECT * FROM LANG_MAST;
INSERT INTO ACT_MAST (act_name)
SELECT DISTINCT (act_name) 
FROM MOVIES
ORDER BY act_name;

INSERT INTO LANG_MAST(LANG)
SELECT DISTINCT(LANG) FROM MOVIES;

INSERT INTO DIR_MAST (DIR_NAME)
SELECT DISTINCT DIR_NAME FROM MOVIES;
 
INSERT INTO MOV_NORM(REL_YEAR,MOV_NAME,ACT_ID,LANG_ID,DIR_ID)
SELECT 
M.REL_YEAR,
M.MOV_NAME,
A.ACT_ID,
L.LANG_ID,
D.DIR_ID
FROM MOVIES AS  M 
JOIN ACT_MAST A ON M.ACT_NAME = A.ACT_NAME
JOIN LANG_MAST L ON M.LANG=L.LANG
JOIN DIR_MAST D ON M.DIR_NAME=D.DIR_NAME;

-- Top SQL Query Questions for Your Movie Table
-- A. Basic SELECT Queries
-- 1. Display all movie details from the table.
SELECT M.REL_YEAR , M.MOV_NAME, A.ACT_NAME , L.LANG , D.DIR_NAME 
FROM MOV_NORM M 
INNER JOIN ACT_MAST AS A ON A.ACT_ID = M.ACT_ID
INNER JOIN LANG_MAST AS L ON L.LANG_ID = M.LANG_ID
INNER JOIN DIR_MAST AS D ON D.DIR_ID = M.DIR_ID;

-- 2. Display only the movie_name and actor_name for all movies.
SELECT M.MOV_NAME , A.ACT_NAME
FROM MOV_NORM M
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID;

-- 3. Show all movies released in the year 2020.
SELECT M.MOV_NAME, M.REL_YEAR , A.ACT_NAME ,L.LANG,D.DIR_NAME
FROM MOV_NORM M 
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID
INNER JOIN LANG_MAST L ON L.LANG_ID = M.LANG_ID
INNER JOIN DIR_MAST D ON D.DIR_ID = M.DIR_ID
WHERE M.REL_YEAR = 2020;

-- 4. Retrieve all movies acted by a specific actor (e.g., “Vijay”).
SELECT M.MOV_NAME, M.REL_YEAR , 
A.ACT_NAME ,L.LANG,D.DIR_NAME
FROM MOV_NORM M 
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID
INNER JOIN LANG_MAST L ON L.LANG_ID = M.LANG_ID
INNER JOIN DIR_MAST D ON D.DIR_ID = M.DIR_ID
WHERE A.ACT_NAME = 'Vijay';

-- 5. List movies directed by a particular director.
SELECT M.MOV_NAME, M.REL_YEAR , A.ACT_NAME ,L.LANG,D.DIR_NAME
FROM MOV_NORM M 
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID
INNER JOIN LANG_MAST L ON L.LANG_ID = M.LANG_ID
INNER JOIN DIR_MAST D ON D.DIR_ID = M.DIR_ID
WHERE D.DIR_NAME = 'Atlee Kumar';

-- 6. Show all movies in the Tamil language.
SELECT M.MOV_NAME, M.REL_YEAR , A.ACT_NAME ,L.LANG,D.DIR_NAME
FROM MOV_NORM M 
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID
INNER JOIN LANG_MAST L ON L.LANG_ID = M.LANG_ID
INNER JOIN DIR_MAST D ON D.DIR_ID = M.DIR_ID
WHERE L.LANG = 'Tamil';

-- 7. Display distinct movie release languages.
SELECT DISTINCT L.LANG
FROM MOV_NORM M 
INNER JOIN LANG_MAST L ON L.LANG_ID = M.LANG_ID;

SELECT * FROM LANG_MAST;

-- 8. Show unique actor names from the table.
SELECT DISTINCT A.ACT_NAME
FROM MOV_NORM M
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID;

SELECT *  FROM ACT_MAST;

-- 9. Show all movies whose name starts with the letter ‘K’.
SELECT M.MOV_NAME, M.REL_YEAR , A.ACT_NAME ,L.LANG,D.DIR_NAME
FROM MOV_NORM M 
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID
INNER JOIN LANG_MAST L ON L.LANG_ID = M.LANG_ID
INNER JOIN DIR_MAST D ON D.DIR_ID = M.DIR_ID
WHERE M.MOV_NAME LIKE 'K%'; 

-- 10. Display all movies released between 2010 and 2020.
SELECT M.MOV_NAME, M.REL_YEAR , A.ACT_NAME ,L.LANG,D.DIR_NAME
FROM MOV_NORM M 
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID
INNER JOIN LANG_MAST L ON L.LANG_ID = M.LANG_ID
INNER JOIN DIR_MAST D ON D.DIR_ID = M.DIR_ID
WHERE M.REL_YEAR BETWEEN 2010 AND 2020;


-- B. Filtering & Sorting
-- 11. Show all movies sorted by release_year in ascending order.
SELECT M.MOV_NAME, M.REL_YEAR , A.ACT_NAME ,L.LANG,D.DIR_NAME
FROM MOV_NORM M 
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID
INNER JOIN LANG_MAST L ON L.LANG_ID = M.LANG_ID
INNER JOIN DIR_MAST D ON D.DIR_ID = M.DIR_ID
ORDER BY M.REL_YEAR;
 
-- 12. Show all movies sorted by movie_name in alphabetical order.
SELECT M.MOV_NAME, M.REL_YEAR , A.ACT_NAME ,L.LANG,D.DIR_NAME
FROM MOV_NORM M 
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID
INNER JOIN LANG_MAST L ON L.LANG_ID = M.LANG_ID
INNER JOIN DIR_MAST D ON D.DIR_ID = M.DIR_ID
ORDER BY M.MOV_NAME;

-- 13. List the latest 10 movies based on release_year.
SELECT M.MOV_NAME, M.REL_YEAR , A.ACT_NAME ,L.LANG,D.DIR_NAME
FROM MOV_NORM M 
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID
INNER JOIN LANG_MAST L ON L.LANG_ID = M.LANG_ID
INNER JOIN DIR_MAST D ON D.DIR_ID = M.DIR_ID
ORDER BY M.REL_YEAR DESC LIMIT 10;

-- 14. List old (earliest) 10 movies.
SELECT M.MOV_NAME, M.REL_YEAR , A.ACT_NAME ,L.LANG,D.DIR_NAME
FROM MOV_NORM M 
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID
INNER JOIN LANG_MAST L ON L.LANG_ID = M.LANG_ID
INNER JOIN DIR_MAST D ON D.DIR_ID = M.DIR_ID
ORDER BY M.REL_YEAR ASC LIMIT 10;

-- 15.Show movies where actor_name contains the word “Khan”.
SELECT M.MOV_NAME, M.REL_YEAR , A.ACT_NAME ,L.LANG,D.DIR_NAME
FROM MOV_NORM M 
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID
INNER JOIN LANG_MAST L ON L.LANG_ID = M.LANG_ID
INNER JOIN DIR_MAST D ON D.DIR_ID = M.DIR_ID
WHERE A.ACT_NAME LIKE  ('%Khan' OR  '%Khan%' OR 'Khan%');

-- C. Aggregate Functions
-- 16. Count the total number of movies in the table.
SELECT COUNT(*) AS TOTAL_MOVIES
FROM MOV_NORM; 

-- 17.Count how many movies are released in each language.
SELECT L.LANG,COUNT(M.MOV_NAME) AS MOVIES_BY_LANG
FROM MOV_NORM M
INNER JOIN LANG_MAST L ON L.LANG_ID = M.LANG_ID
GROUP BY L.LANG;

-- 18. Find the number of movies acted by each actor.
SELECT A.ACT_NAME,COUNT(M.MOV_NAME)
FROM MOV_NORM M
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID
GROUP BY ACT_NAME;

-- 19. Find the number of movies directed by each director.
SELECT D.DIR_NAME ,COUNT(*) AS MOVIES_DIRECTED
FROM MOV_NORM M 
INNER JOIN DIR_MAST D ON D.DIR_ID = M.DIR_ID
GROUP BY D.DIR_NAME;

-- 20. Find how many movies were released each year.
SELECT M.REL_YEAR , COUNT(*) AS MOVIES_RELEASED
FROM MOV_NORM M 
GROUP BY M.REL_YEAR;

-- 21. Identify the year with the highest number of movie releases.
SELECT M.REL_YEAR , COUNT(*) AS HIGHEST_NO_OF_MOVIES
FROM MOV_NORM M 
GROUP BY M.REL_YEAR
ORDER BY COUNT(*) DESC
LIMIT 10;

-- 22. Find the actor who acted in the most movies.
SELECT A.ACT_NAME,COUNT(A.ACT_NAME) AS MOST_ACTED_ACTOR
FROM MOV_NORM M 
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID
GROUP BY ACT_NAME
ORDER BY COUNT(A.ACT_NAME) DESC
LIMIT 1;

-- 23. Find the director with the maximum number of films.
SELECT D.DIR_NAME ,COUNT(DIR_NAME) 
FROM MOV_NORM M 
INNER JOIN DIR_MAST D ON D.DIR_ID = M.DIR_ID
GROUP BY D.DIR_NAME 
ORDER BY COUNT(DIR_NAME) DESC
LIMIT 3;

-- D. GROUP BY + HAVING
-- 24. List languages that have more than 100 movies.
SELECT L.LANG , COUNT(*) AS LANGUAGES_MORETHAN_100
FROM MOV_NORM M 
INNER JOIN LANG_MAST AS L ON L.LANG_ID = M.LANG_ID
GROUP BY L.LANG
HAVING COUNT(*) > 100;

-- 25. List actors who acted in more than 10 movies.
SELECT A.ACT_NAME , COUNT(*) AS ACTOR_MORETHAN_10
FROM MOV_NORM M 
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID
GROUP BY A.ACT_NAME
HAVING COUNT(*) > 10;

-- 26. List directors who directed at least 5 movies.
SELECT D.DIR_NAME , COUNT(*) AS DIRECTOR_ATLEAT5MOVIES
FROM MOV_NORM M 
INNER JOIN DIR_MAST D ON D.DIR_ID = M.DIR_ID
GROUP BY D.DIR_NAME
HAVING COUNT(*) >= 5;

-- 27. Find years where more than 50 movies were released.
SELECT M.REL_YEAR , COUNT(*) AS RELEASE_YEAR_MORETHAN50
FROM MOV_NORM M 
GROUP BY M.REL_YEAR
HAVING COUNT(*) > 50;

-- 28. List actors who have worked in more than 3 languages.
SELECT A.ACT_NAME , COUNT( DISTINCT L.LANG) AS TOTAL_LANGUAGES
FROM MOV_NORM M 
INNER JOIN ACT_MAST A ON A.ACT_ID = M.ACT_ID
INNER JOIN LANG_MAST L ON L.LANG_ID = M.LANG_ID
GROUP BY A.ACT_NAME
HAVING COUNT( DISTINCT L.LANG) > 3
ORDER BY TOTAL_LANGUAGES DESC ;
